transfer to excel file
DavidShim-Personal/Samonim pull request #2
Opened 2024-07-18 08:04 UTC by DHCHO-pt

transfer to excel file

2024-07-18 10:04 UTC, DavidShim-Personal requested changes
수정할 것들이 좀 있어요! 수정해서 commit/push 하면 pull request에 반영될테니 작업해서 푸시해주세요.

2024-07-18 10:04 UTC, DavidShim-Personal commented on main.py
> +        existing_df = pd.read_excel(file_name, header=None)
이렇게 하면 동작은 하는데, 매번 엑셀 파일을 새로 읽어와야 해서 나중에 row가 추가될 수록 비효율이 더 많이 보일 것 같아?

매번 pd.read_excel을 하지 않고, 처음에 한번은 파일을 만들어주고, 이후 부터는 이 df 변수를 갖고 있어서 매번 concat만 하도록 수정해주세요

2024-07-18 10:04 UTC, DavidShim-Personal commented on main.py
> +def save_to_excel(data, file_name='output.xlsx', sheet_name='Sheet1'):
save_to_excel 함수는 왜 2개인가요?

2024-07-18 10:04 UTC, DavidShim-Personal commented on main1.py
mani1.py는 왜 필요해요? 필요 없으면 삭제하거나 commit 할 때 얘는 제외하고 반영하는 게 좋을듯 합니다

2024-07-18 10:04 UTC, DavidShim-Personal commented on 개인연습.py
개인 연습도 빼고 반영해주세요!

2024-07-19 09:00 UTC, DavidShim-Personal requested changes
파일 삭제는 확인했는데, 기타 main.py에서 수정 되어야 할 부분들이 반영이 안된 것 같아요.
수정하고 다시 commit/push 해주세요! (왜 누락됐었는지도 pull request에 comment 남겨주세요. 작업은 했는데 commit을 안했다던지, 작업을 깜빡했다던지).

2024-07-19 09:00 UTC, DavidShim-Personal commented on main.py
> +        existing_df = pd.read_excel(file_name, header=None)
동혁아 이건 고쳐진 거니? 코드는 이전이랑 똑같아 보이는데 반영이 안 된건가?

2024-07-19 09:00 UTC, DavidShim-Personal commented on main.py
> +# 사용 예제
여기도 테스트 코드가 그대로 보여요 ㅎㅎ pull request에 변경점이 반영됐는지 확인하고 resolve 처리 해주세요!

2024-07-19 09:00 UTC, DavidShim-Personal commented on main.py
> +def save_to_excel(data, file_name='output.xlsx', sheet_name='Sheet1'):
여기도!

2024-07-23 12:42 UTC, onyouham approved these changes

2024-07-26 23:33 UTC, DavidShim-Personal approved these changes
아직 반영할 것들이 좀 남은 것 같지만.. 우선 넣고 다 같이 검증하죠.

2024-07-30 12:58 UTC, merged